name: Reference check

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        shell: pwsh
        run: |
          .\check.ps1
          
  test-report:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    name: Test reports ${{ github.job }}
    steps:
      - name: print job.id
        run: |
          echo "job ID: ${{ job.id }}"
      - name: print github.job
        run: |
          echo "github job: ${{ github.job }}"
  
