name: Reference check again

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      - uses: gkurbesov/gha-test@main
      - name: Print completed
        shell: pwsh
        run: |
          Write-Host "Job is completed"
