name: Reference check again

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      - uses: gkurbesov/gha-test@main
      - name: Print completed
        shell: pwsh
        run: |
          for ($i = 1; $i -le 100; $i++ ) {
              Write-Progress -Activity "Search in Progress" -Status "$i% Complete:" -PercentComplete $i
              Start-Sleep -Milliseconds 250
          }
          Write-Host "\u001b[35mJob is completed"
