name: Reference check again

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      - uses: gkurbesov/gha-test@main
      - name: Print completed
        shell: pwsh
        run: |
          Write-Host "\u001b[35mJob is completed"
          Write-Output "\u001b[35mJob is completed-2"
          
  test-report:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    name: Test reports ${{ github.job }}
    steps:
      - name: print job.id
        run: |
          echo "job ID: ${{ github.workflow }}"
      - name: print github.job
        run: |
          echo "github job: ${{ github.job }}"
