name: 'Test PWSH'

on: workflow_dispatch

jobs:

  build:
    name: 'Test PWSH'
    runs-on: ubuntu-latest
    timeout-minutes: 5
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install
        run: snap install powershell --classic
      - name: Version
        run: pwsh -v
